version: '3.8'

services:
  kafka-1:
    image: bitnami/kafka:latest
    container_name: kafka-1
    ports:
      - "9092:9092"
    env_file:
      - environment.env
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=LOREMIPSUMDOLORSITAMET
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=2@kafka-2:9093,1@kafka-1:9093
#      - http://localhost:8080/employee/update/{{id}}
      - KAFKA_CFG_LISTENERS=INTERNAL://:9091,EXTERNAL://:9092,CONTROLLER://:9093
#      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka-1:9091,EXTERNAL://${HOSTNAME:-localhost2}:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka-1:9091,EXTERNAL://host.docker.internal:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
    volumes:
      - ./kafka_data/kafka-1:/bitnami/kafka
  kafka-2:
    image: bitnami/kafka:latest
    container_name: kafka-2
    ports:
      - "9094:9094"
    env_file:
      - environment.env
    environment:
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_KRAFT_CLUSTER_ID=LOREMIPSUMDOLORSITAMET
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
#      - http://localhost:8080/employee/update/{{id}}
      - KAFKA_CFG_LISTENERS=INTERNAL://:9091,EXTERNAL://:9094,CONTROLLER://:9093
#      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka-1:9091,EXTERNAL://${HOSTNAME:-localhost2}:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka-2:9091,EXTERNAL://host.docker.internal:9094
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
    volumes:
      - ./kafka_data/kafka-2:/bitnami/kafka

  kafka-3:
    image: bitnami/kafka:latest
    container_name: kafka-3
    ports:
      - "9095:9095"
    env_file:
      - environment.env
    environment:
      - KAFKA_CFG_NODE_ID=3
      - KAFKA_KRAFT_CLUSTER_ID=LOREMIPSUMDOLORSITAMET
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
#      - http://localhost:8080/employee/update/{{id}}
      - KAFKA_CFG_LISTENERS=INTERNAL://:9091,EXTERNAL://:9095,CONTROLLER://:9093
#      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka-1:9091,EXTERNAL://${HOSTNAME:-localhost2}:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka-3:9091,EXTERNAL://host.docker.internal:9095
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
    volumes:
      - ./kafka_data/kafka-3:/bitnami/kafka

#  db:
#    image: postgres:16-alpine
#    restart: unless-stopped
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: password-secret
#      POSTGRES_DB: spring_framework_6_db
#    ports:
#      - "6543:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: