spring:
  application:
    name: auth_server
  output:
    ansi:
      enabled: always
#  security:
#    user:
#      name: user1
#      password: password


logging:
  level:
    org.springframework.security: trace

server:
  port: 9000